# Generated by Django 2.2.12 on 2021-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('difficulty', models.IntegerField(default=1)),
                ('content', models.TextField()),
            ],
        ),
    ]
